env:
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "jest"
rules: {  import/extensions: 0,
  no-underscore-dangle: 0,
  no-console: 0
}
